steps:
  - id: 'Build docker image'
    name: 'gcr.io/cloud-builders/docker'
    args: ["build", "-t", "gcr.io/$PROJECT_ID/angular-app:$BUILD_ID", ".", "-f", "Dockerfile.stage"]

images: ["gcr.io/$PROJECT_ID/angular-app:$BUILD_ID"]